### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by fly7632785** [vivian8725118/TimeLine#5]
`
 java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getBottom()' on a null object reference
                                                                    at com.vivian.timelineitemdecoration.itemdecoration.DotItemDecoration.drawHorizontal(DotItemDecoration.java:140)
                                                                    at com.vivian.timelineitemdecoration.itemdecoration.DotItemDecoration.onDraw(DotItemDecoration.java:125)
                                                                    at android.support.v7.widget.RecyclerView.onDraw(RecyclerView.java:3722)
                                                                    at android.view.View.draw(View.java:17185)
                                                                    at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:3657)
`

**Comment by vivian8725118** [comment]
can you reproduce that?

**Comment by fly7632785** [comment]
是的，空指针，多次使用都是   检查了一下代码 ，
![e9c4a72b-cc16-41ec-8d21-afbff6f3ea8c](https://user-images.githubusercontent.com/10276266/27894575-8bbb8850-623f-11e7-8444-345f197b768f.png)

这里最好加个判断，childCount为0的时候 
`
   final int childCount = parent.getChildCount();
`
为空  所以空指针了

**Comment by fly7632785** [comment]
至于为什么 getChildCount 为0 没有深人探究   
猜测是不是那时候 还没有把子view加载出来

**Comment by vivian8725118** [comment]
好的，我加个判断

**Comment by qinyang1018** [comment]
这个问题我也遇见了

**Comment by qinyang1018** [comment]
![image](https://user-images.githubusercontent.com/15726024/27915356-9f762d7e-6298-11e7-9dac-923299b044ea.png)
我是这个lastChild为null了

**Comment by vivian8725118** [comment]
这个现在加上判断了
