### ISSUE TITLE
关于DotItemDecoration.java 

### ISSUE THREAD

**Issue by BigChaChi** [vivian8725118/TimeLine#9]
你好，当Adapter的tem数目小于2时，会抛出
` java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getBottom()' on a null object reference
                                                                                 at com.vivian.timelineitemdecoration.itemdecoration.DotItemDecoration.drawVerticalItem(DotItemDecoration.java:205)
                                                                                 at com.vivian.timelineitemdecoration.itemdecoration.DotItemDecoration.onDraw(DotItemDecoration.java:157)`

**Comment by vivian8725118** [comment]
1.4版本已经修改了这个bug
